# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DH5CYEd2E2NI68wIdzOl9ujcavuGQBAi
"""

import streamlit as st
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

st.title('SVM Classifier')

# Load dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train SVM model
clf = SVC()
clf.fit(X_train, y_train)

# Make predictions
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

st.write('Accuracy:', accuracy)

# Sidebar
st.sidebar.header('User Input')
def get_user_input():
    sepal_length = st.sidebar.slider('Sepal Length', float(iris.data[:,0].min()), float(iris.data[:,0].max()), float(iris.data[:,0].mean()))
    sepal_width = st.sidebar.slider('Sepal Width', float(iris.data[:,1].min()), float(iris.data[:,1].max()), float(iris.data[:,1].mean()))
    petal_length = st.sidebar.slider('Petal Length', float(iris.data[:,2].min()), float(iris.data[:,2].max()), float(iris.data[:,2].mean()))
    petal_width = st.sidebar.slider('Petal Width', float(iris.data[:,3].min()), float(iris.data[:,3].max()), float(iris.data[:,3].mean()))
    return sepal_length, sepal_width, petal_length, petal_width

user_input = get_user_input()
prediction = clf.predict([user_input])

st.write('Predicted Class:', iris.target_names[prediction[0]])